{"name": "test03_mis_audit", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x000001CB0FEC0320>\n\n    def test03_mis_audit(self):\n        # 1. 调用审核文章接口\n        r = self.mis.api_mis_audit()\n        try:\n            # 2. 断言\n>           Tool.common_assert(r)\n\nscripts\\test02_mis.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'tool.tool.Tool'>, response = <Response [403]>, status_code = 201\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:23: AssertionError"}, "attachments": [{"name": "log", "source": "8b4b1b03-9007-4ae6-b0ad-3fa2a4a4cf33-attachment.txt", "type": "text/plain"}], "start": 1612504609822, "stop": 1612504609922, "uuid": "20f193f3-eeb6-47b3-bbb0-02fccc8f4181", "historyId": "b465eea778f8ece01716f4527f84b689", "testCaseId": "90ff882230c9f80dbc7a2baf9bff7e41", "fullName": "scripts.test02_mis.TestMis#test03_mis_audit", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "DESKTOP-0Q83GN5"}, {"name": "thread", "value": "4324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}