{"name": "test02_mis_search", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x000001B35F9586A0>\n\n    def test02_mis_search(self):\n        # 1. 调用查询文章接口\n        r = self.mis.api_mis_search()\n        print(\"查询文章成功后：\", r.json())\n        try:\n            # 2. 断言\n>           Tool.common_assert(r, status_code=200)\n\nscripts\\test02_mis.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'tool.tool.Tool'>, response = <Response [403]>, status_code = 200\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:23: AssertionError"}, "attachments": [{"name": "log", "source": "774821eb-de1c-4822-a327-db633818b8ed-attachment.txt", "type": "text/plain"}], "start": 1612504861560, "stop": 1612504861670, "uuid": "6a0d4c94-67a8-400c-aea9-e7198a87c861", "historyId": "3f73d307b052a1555ac345fb66f890ec", "testCaseId": "717bcced00d6f137cd9d7d4949eeb939", "fullName": "scripts.test02_mis.TestMis#test02_mis_search", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "DESKTOP-0Q83GN5"}, {"name": "thread", "value": "5104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}