2021-02-01 11:58:16,807 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 11:58:16,807 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 11:58:16,807 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 11:58:16,907 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 11:58:53,484 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 11:58:53,484 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 11:58:53,484 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 11:58:53,624 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTkyNTUsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.O8H8wUh2DvgJgsB4_gSV-EBbslEkh6X294zSJrS3VUM'}
2021-02-01 11:58:53,624 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:07:41,154 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:07:41,154 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:07:41,154 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:07:41,454 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:07:41,494 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:07:49,973 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:07:49,973 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:07:49,973 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:07:50,083 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk3OTIsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.uV2TXDrOo1Te64ctpiX1Bn3k3iewg4VhGaCYtfk4yN0'}
2021-02-01 12:07:50,083 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:07:50,093 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:07:54,023 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:07:54,023 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:07:54,023 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:07:54,123 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:07:54,173 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:07:57,183 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:07:57,183 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:07:57,183 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:07:57,293 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:07:57,333 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:07:59,223 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:07:59,223 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:07:59,223 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:07:59,333 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:07:59,373 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:01,372 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:01,372 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:01,372 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:01,472 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4MDMsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.VKDW0FV_nGl3pcob5oOoxqOL0TpnihBddZ9j-zNKPFI'}
2021-02-01 12:08:01,482 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:08:01,482 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:06,242 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:06,242 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:06,242 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:06,352 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:08:06,392 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:41,590 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:41,590 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:41,590 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:41,700 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:08:41,740 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:44,880 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:44,880 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:44,890 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:45,000 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4NDcsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.8WR0gEqbq93l-enSL_ejgC_omJ5mOR3WiZDLYFWeCko'}
2021-02-01 12:08:45,000 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:08:45,010 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:52,299 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:52,299 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:52,299 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:52,409 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:08:52,449 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:54,939 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:54,939 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:54,949 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:55,049 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:08:55,099 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:56,759 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:56,769 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:56,769 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:56,869 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:08:56,919 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:08:58,479 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:08:58,479 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:08:58,479 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:08:58,589 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4NjAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.pmTggEESdCH3r74GG1QR-PwEIDxL-HqNaBDKvhLrcLc'}
2021-02-01 12:08:58,589 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:08:58,599 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:00,259 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:00,259 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:00,259 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:00,369 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:00,409 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:02,559 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:02,559 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:02,559 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:02,669 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:02,719 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:04,319 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:04,319 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:04,319 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:04,429 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:04,469 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:06,379 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:06,379 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:06,379 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:06,499 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4NjgsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.w3ynuCRckV3vq4DfOoy-yBTrPowdm2P5uTFLazRmrMM'}
2021-02-01 12:09:06,499 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:09:06,509 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:09,018 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:09,018 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:09,018 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:09,128 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:09,168 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:10,648 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:10,648 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:10,648 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:10,758 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4NzMsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.gomF7i-FnRJXkxKbQ2M25orKrXceiiBAgjHbmXtB2uY'}
2021-02-01 12:09:10,758 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:09:10,768 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:15,158 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:15,158 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:15,158 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:15,268 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:15,318 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:16,898 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:16,898 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:16,898 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:17,008 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:17,058 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:24,677 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:24,677 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:24,677 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:24,798 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:24,847 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:28,057 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:28,057 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:28,057 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:28,177 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNTk4OTAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.9vCwj9M14jVcbHLwUUsdHWvhBRaS7xobWGNNxyExDmE'}
2021-02-01 12:09:28,177 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:09:28,187 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:31,127 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:31,127 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:31,127 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:31,237 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:31,277 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:37,077 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:37,077 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:37,087 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:37,197 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:37,237 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:09:38,977 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:09:38,977 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:09:38,977 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:09:39,077 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:09:39,127 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:10:24,234 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:10:24,234 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:10:24,234 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:11:54,346 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:11:54,346 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:11:54,346 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:13:21,441 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:13:21,441 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:13:21,441 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:13:21,561 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:13:21,601 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:14:29,066 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:14:29,066 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:14:29,066 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:14:29,176 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:14:29,216 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'image': []}}
2021-02-01 12:20:49,392 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:20:49,392 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:20:49,392 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:20:49,522 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:20:49,562 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:20:52,672 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:20:52,672 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:20:52,672 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:20:52,782 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:20:52,832 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:20:55,501 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:20:55,501 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:20:55,501 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:20:55,612 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjA1NzcsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.i9sDOutGacUOkVjwIfZE7UEooeUdXRgSTACPIIO9uOk'}
2021-02-01 12:20:55,612 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:20:55,621 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:20:55,732 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:25:46,124 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:25:46,124 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:25:46,124 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:25:46,224 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjA4NjgsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.n7I3VJE-0XlSRmV3JHzqkbFPjtRS99DFWrxiUaX6QnY'}
2021-02-01 12:25:46,224 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:25:46,234 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:25:46,334 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:25:52,584 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:25:52,584 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:25:52,584 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:25:52,694 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:25:52,734 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:25:55,353 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:25:55,353 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:25:55,353 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:25:55,453 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 12:25:55,493 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:25:57,723 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 12:25:57,723 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 12:25:57,723 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 12:25:57,843 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjA4ODAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.CzcRjS-i3p3eJUzsa2qIal5AXS-Ma_AwUC7COvBo8gE'}
2021-02-01 12:25:57,843 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 12:25:57,843 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试！', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 12:25:57,953 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 13:33:06,873 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:06,873 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:06,874 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:07,002 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 13:33:07,048 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:09,907 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:09,907 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:09,908 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:10,002 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 13:33:10,048 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:12,168 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:12,168 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:12,169 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:12,276 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 13:33:12,321 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:13,928 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:13,929 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:13,930 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:14,032 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 13:33:14,077 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:15,547 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:15,548 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:15,548 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:15,651 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 13:33:15,695 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:17,120 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 13:33:17,120 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 13:33:17,121 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 13:33:17,226 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjQ5MTksInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.gg9GwXq069_t2MAmvfPAqoWJGoOAWsbkKJouohhtseY'}
2021-02-01 13:33:17,226 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 13:33:17,233 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 13:33:17,341 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:13:34,837 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:13:34,838 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:13:34,838 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:13:34,976 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjczMzcsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.WmCdY5Y75t-fhOX6uUrK6lxhl9Ox1Q3X1qz3RkXm7e8'}
2021-02-01 14:13:34,976 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:13:34,983 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:13:35,115 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:13:35,319 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjczMzYsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.HDPaBQJQvZ-B4jsQj0c0srIg_7L-Bk6AryS0-9BzOnc'}
2021-02-01 14:13:35,320 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:24:11,505 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:24:11,505 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:24:11,506 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:24:11,633 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:24:11,678 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:24:11,777 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:24:11,777 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:24:11,777 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:24:11,778 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:24:11,996 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjc5NzQsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.JgNbJSf76ya3rWFxHuqWqEdFNfyWwMJJ8j157zPJAag'}
2021-02-01 14:24:11,997 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:24:14,897 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:24:14,897 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:24:14,898 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:24:15,007 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:24:15,062 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:24:15,163 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:24:15,163 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:24:15,163 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:24:15,164 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:24:15,360 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjc5NzYsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.rQTyvEqkH1ni1T_esa7AbdAw2rQ-YTem2FJTFj50Kvk'}
2021-02-01 14:24:15,360 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:24:18,272 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:24:18,272 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:24:18,273 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:24:18,377 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjc5ODAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.cDxN8Rsgaoc0M3GXh6zv6QZFyLI5gipuu0bWltof0y0'}
2021-02-01 14:24:18,377 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:24:18,383 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:24:18,483 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:24:18,490 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:24:18,491 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:24:18,491 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:24:18,491 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:24:18,716 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjc5ODEsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.4zKI3xjuvhk1X-39HhlZwLCU3lAJnwIZf3S_ZyqtI-Y'}
2021-02-01 14:24:18,717 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:17,277 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:34:17,277 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:34:17,278 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:34:17,436 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:34:17,481 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:34:17,576 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:34:17,576 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:34:17,576 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:34:17,577 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:34:17,788 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg1ODAsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.VElIB7d-wRMh0Pb31M3PNzg7H2E14OWf2xp9R0oe06s'}
2021-02-01 14:34:17,789 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:17,796 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:34:17,901 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:17,901 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:34:17,911 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:34:33,799 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:34:33,799 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:34:33,800 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:34:33,905 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:34:33,950 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:34:34,054 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:34:34,055 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:34:34,055 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:34:34,055 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:34:34,254 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg1OTUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.1mHAPaMDm0kg4PExHq7hU7_06oS4NuYL7jRlpbXYyt4'}
2021-02-01 14:34:34,255 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:34,262 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:34:34,364 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:34,365 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:34:34,374 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:34:49,512 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:34:49,513 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:34:49,513 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:34:49,626 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:34:49,672 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:34:49,786 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:34:49,786 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:34:49,786 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:34:49,787 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:34:49,994 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2MTEsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.we9k4RoMlB6UphQVw5QQlWzDdcpH07bQR4zi5Ux0VEo'}
2021-02-01 14:34:49,994 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:50,002 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:34:50,104 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:34:50,104 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:34:50,113 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:35:20,299 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:35:20,299 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:35:20,300 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:35:20,409 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2NDIsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.KCDHa-0E4dAUj5I1Vke6Ifgy5DYBYHH6CoCvrndZfsY'}
2021-02-01 14:35:20,409 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:20,418 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:35:20,513 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:20,519 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:35:20,520 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:35:20,520 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:35:20,521 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:35:20,724 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2NDIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.E98JHTxPS0PVJ5QSwZBBYmO6G8V_TI4GifF2ttnTcg4'}
2021-02-01 14:35:20,725 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:20,732 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:35:20,840 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:20,840 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:35:20,881 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [1356129499376254976], 'status': 2}
2021-02-01 14:35:35,790 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:35:35,790 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:35:35,791 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:35:35,895 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:35:35,940 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:35:36,042 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:35:36,043 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:35:36,043 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:35:36,044 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:35:36,241 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2NTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.YPE2MTFG1_pTAuVAZwKYbgtVD5mevDRNtjEIrG48c6U'}
2021-02-01 14:35:36,242 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:36,249 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:35:36,365 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:36,365 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:35:36,374 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:35:51,321 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:35:51,322 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:35:51,322 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:35:51,428 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:35:51,472 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:35:51,566 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:35:51,566 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:35:51,566 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:35:51,567 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:35:51,763 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2NzQsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.O9ftw0WeGb-QoTE4KR1TXPRe8H3rRctxvrIstHnQ-B0'}
2021-02-01 14:35:51,764 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:51,771 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:35:51,874 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:35:51,874 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:35:51,883 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:36:07,806 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:36:07,807 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:36:07,807 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:36:07,912 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:36:07,970 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:36:08,062 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:36:08,062 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:36:08,062 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:36:08,063 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:36:08,260 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg2ODksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.O1lSoeVZgPja-2YzEkGoiJkCsB_Vy-27eEXdw1QRLzU'}
2021-02-01 14:36:08,261 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:08,269 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:36:08,383 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:08,383 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:36:08,392 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:36:37,570 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:36:37,570 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:36:37,571 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:36:37,678 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:36:37,730 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:36:37,834 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:36:37,834 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:36:37,834 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:36:37,835 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:36:38,033 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg3MTksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.V6HMu0L8LUARCjq1pp5lJQCV-ix-xarkfoQ-DEjVwB4'}
2021-02-01 14:36:38,035 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:38,042 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:36:38,143 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:38,144 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:36:38,153 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:36:54,749 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:36:54,749 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:36:54,750 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:36:54,863 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg3MzcsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.T3MMX8MNwuuKO3d7voJW4B7sksQChx370A2hX-U-0b0'}
2021-02-01 14:36:54,864 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:54,871 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:36:54,976 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:54,983 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:36:54,983 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:36:54,983 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:36:54,984 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:36:55,198 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg3MzcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Cu8TReZCtHZ7Dg72HgqnCfSP909hsYR4NHlZAI-9xWE'}
2021-02-01 14:36:55,199 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:55,206 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:36:55,306 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:36:55,306 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:36:55,349 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [1356129892260904960], 'status': 2}
2021-02-01 14:37:27,715 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:37:27,716 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:37:27,716 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:37:27,822 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:37:27,868 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:37:27,972 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:37:27,972 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:37:27,972 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:37:27,973 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:37:28,176 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg3NjksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.qjmBlVO1AtLob9oIT7PaU1F7sOQK9-uFfW_Cj7qzCCI'}
2021-02-01 14:37:28,177 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:37:28,183 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:37:28,297 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:37:28,297 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:37:28,306 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:37:47,285 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:37:47,285 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:37:47,286 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:37:47,390 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:37:47,434 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:37:47,537 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:37:47,538 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:37:47,538 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:37:47,539 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:37:47,742 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg3ODgsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.hZLhW3qkT72Qw6WSpZ3Jjq51u791ZKdUw_qK3C3rQfk'}
2021-02-01 14:37:47,743 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:37:47,750 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:37:47,861 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:37:47,861 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:37:47,870 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:38:11,836 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:38:11,836 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:38:11,837 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:38:11,940 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:38:11,984 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:38:12,081 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:38:12,081 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:38:12,081 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:38:12,082 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:38:12,287 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjg4MTMsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.2CJuNHI7UKPZ6Jt5S22hG0DUxtpaLJVqF2AxOZVj2Js'}
2021-02-01 14:38:12,288 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:38:12,294 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:38:12,393 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:38:12,393 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:38:12,403 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:42:05,686 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:42:05,686 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:42:05,687 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:42:05,793 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:42:05,838 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:42:05,935 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:42:05,935 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:42:05,935 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:42:05,936 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:42:06,142 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjkwNDcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Y1es_og4cpJr1DMxkjjOLf0-w61zRikgGMi7cFEewxs'}
2021-02-01 14:42:06,143 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:42:06,150 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:42:21,250 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:42:21,250 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:42:21,260 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [None], 'status': 2}
2021-02-01 14:43:14,420 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:43:14,421 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:43:14,421 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:43:14,534 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjkxMTcsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.qTMixr9NrZaD_w3JWvgkP73-2JLd6a2aE0WASBztfhY'}
2021-02-01 14:43:14,534 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:43:14,542 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:43:14,647 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:43:14,654 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:43:14,654 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:43:14,654 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:43:14,655 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:43:14,855 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjkxMTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.ZKisYdDhJ1pezRwRUlfLZ96m-Aca8PV6Kxe5gmSBEbM'}
2021-02-01 14:43:14,855 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:43:14,863 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:43:14,968 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:43:14,968 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:43:15,010 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [1356131482518683648], 'status': 2}
2021-02-01 14:46:17,525 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:46:17,527 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:46:17,528 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:46:17,664 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjkzMDAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.cxl4DaNA8714_6naKt2_zlm72qVybbePTww8H3AEhyM'}
2021-02-01 14:46:17,664 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:46:17,671 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:46:17,778 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:46:17,785 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:46:17,785 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:46:17,785 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:46:17,786 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:46:17,986 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjkyOTksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Ck1xm14k_6T6WslT1iTuMro-SOfmkDn_Y14Gff3b-Oo'}
2021-02-01 14:46:17,987 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:46:17,994 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:46:18,094 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:46:18,095 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:46:18,136 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_id': [1356132252848750592], 'status': 2}
2021-02-01 14:48:14,196 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:48:14,196 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:48:14,197 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:48:14,304 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:48:14,351 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:48:14,450 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:48:14,450 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:48:14,451 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:48:14,451 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:48:14,646 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk0MTUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.o-jO7GQ7Ty_rZhxeFa55dsqQ84hvwAkdzS4-AibJM8I'}
2021-02-01 14:48:14,647 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:14,654 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:48:14,751 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:14,751 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:48:14,761 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 14:48:30,232 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:48:30,233 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:48:30,233 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:48:30,342 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk0MzIsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.ODAWEwS9qprbkiZpIA5nDcJ9TjRZedlu1HYtWkrkqHo'}
2021-02-01 14:48:30,342 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:30,349 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:48:30,447 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:30,454 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:48:30,454 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:48:30,455 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:48:30,455 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:48:30,642 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk0MzIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.XkJ-mLoB2Y1sVXfVYCYO60qPi8OHuQsGaG7Lzo_tKA0'}
2021-02-01 14:48:30,643 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:30,650 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:48:30,741 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:48:30,741 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:48:30,782 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356132809336422400], 'status': 2}
2021-02-01 14:51:17,820 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:51:17,821 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:51:17,821 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:51:17,926 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk2MDAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.YwHtxtK_JdJ5dlGHDdTOytMwylFNwxuE7RC2mb0Jzbw'}
2021-02-01 14:51:17,926 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:51:17,933 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:51:18,036 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:51:18,042 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:51:18,042 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:51:18,042 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:51:18,043 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:51:18,235 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk1OTksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.A16tDLtpuYObry74W8Wk8g7SYUcURUzbelfFCxT5fW8'}
2021-02-01 14:51:18,236 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:51:18,244 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:51:18,351 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:51:18,352 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:51:18,393 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356133515535581184], 'status': 2}
2021-02-01 14:52:57,970 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:52:57,971 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:52:57,972 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:52:58,071 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:52:58,116 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:52:58,221 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:52:58,221 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:52:58,221 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:52:58,222 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:52:58,429 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk3MDAsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.VN1vC66ZCqtlK4QLObJKqRNjrcsXqceZncLsFAsnmoU'}
2021-02-01 14:52:58,430 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:52:58,438 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:52:58,544 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:52:58,544 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:52:58,554 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 14:53:16,141 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:53:16,141 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:53:16,142 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:53:16,258 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk3MTgsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.qpeAzqeM41TFU2PRMRkz42oGpqweWr7UuVqK1kB8Edo'}
2021-02-01 14:53:16,258 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:53:16,267 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:53:16,371 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:53:16,378 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:53:16,378 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:53:16,378 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:53:16,379 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:53:16,599 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNjk3MTksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Z7cWiiINg46Zh-Qdqw1qpoa6d9c2qtEQi1DycCNwT1c'}
2021-02-01 14:53:16,600 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:53:16,607 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:53:16,711 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:53:16,711 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:53:16,752 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356134011876933632], 'status': 2}
2021-02-01 14:58:24,330 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:58:24,330 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:58:24,331 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:58:24,473 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:58:24,519 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:58:24,625 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:58:24,625 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:58:24,626 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:58:24,626 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:58:24,827 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAwMjUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.vPCrrEcl2XTiITiLMI5TDjfqYBaRkqPAcL-GiiMGrFI'}
2021-02-01 14:58:24,828 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:58:24,835 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:58:24,943 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:58:24,943 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:58:24,952 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 14:58:38,907 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 14:58:38,907 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 14:58:38,908 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 14:58:39,007 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 14:58:39,052 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 14:58:39,160 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 14:58:39,160 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 14:58:39,161 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 14:58:39,161 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 14:58:39,372 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAwNDAsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.2BcyRvnoeXJEcIcxwRUUezCovBXAmyNnP0JSXtK29pE'}
2021-02-01 14:58:39,373 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:58:39,381 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 14:58:39,473 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 14:58:39,473 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 14:58:39,483 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:00:59,089 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:00:59,090 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:00:59,091 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:00:59,192 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:00:59,235 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:00:59,337 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:00:59,338 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:00:59,338 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:00:59,339 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:00:59,557 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAxODIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.yO5ouHhasy65r_tkgKlPtBsWxkyWovytwFyVWvLly0s'}
2021-02-01 15:00:59,558 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:00:59,565 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:00:59,663 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:00:59,663 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:00:59,672 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:01:13,775 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:01:13,775 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:01:13,776 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:01:13,875 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:01:13,923 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:01:14,025 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:01:14,026 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:01:14,026 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:01:14,027 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:01:14,227 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAxOTUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.VE1OYmR7Z6Ct-12AtCV5Ri407zX0S51EHcf_ej9VPoA'}
2021-02-01 15:01:14,228 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:01:14,235 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:01:14,343 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:01:14,343 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:01:14,352 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:03:00,446 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:03:00,446 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:03:00,446 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:03:00,556 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:03:00,606 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:03:00,716 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:03:00,716 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:03:00,716 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:03:00,716 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:03:00,926 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAzMDMsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.ub-qO_R7fu7HRRGI_B8cxzbPK9N5IYpUh7BUz0r8e4E'}
2021-02-01 15:03:00,936 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:00,936 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:03:01,036 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:01,036 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:03:01,056 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:03:26,364 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:03:26,364 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:03:26,364 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:03:26,464 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:03:26,514 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:03:26,614 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:03:26,614 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:03:26,614 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:03:26,614 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:03:26,814 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAzMjksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Q1dr7SVyYpX20npXBfp8gdnTzMCVZL_K9rrJmul-4Yo'}
2021-02-01 15:03:26,814 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:26,814 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:03:26,924 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:26,924 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:03:26,934 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:03:40,793 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:03:40,793 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:03:40,793 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:03:40,894 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:03:40,943 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:03:41,043 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:03:41,043 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:03:41,043 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:03:41,043 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:03:41,253 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzAzNDIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.kQ19u4g8F9cKl9tAKXMx-E-bScEk3dYdTarAquE0tMU'}
2021-02-01 15:03:41,253 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:41,253 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:03:41,354 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:03:41,354 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:03:41,363 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:09:28,352 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:09:28,352 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:09:28,353 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:09:28,487 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:09:28,533 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:09:28,626 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:09:28,626 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:09:28,627 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:09:28,627 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:09:28,826 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzA2ODksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.-oiOEcj8xIwEHwJFspr_tYPAVt-3dr94XTcWEsDKRzU'}
2021-02-01 15:09:28,827 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:09:28,834 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:09:28,933 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:09:28,934 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:09:28,943 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:10:01,980 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:10:01,980 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:10:01,981 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:10:02,088 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzA3MjQsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.dYRYCYv_koBiB6qWJGQgrudiN-VmdwYQOg6eaGM_bps'}
2021-02-01 15:10:02,089 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:10:02,096 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:10:02,208 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:10:02,214 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:10:02,215 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:10:02,215 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:10:02,215 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:10:02,425 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzA3MjMsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Nj2jmDPXh2H8wdVbhEqy-rpHMg6zjdRDArR-PB_5J-M'}
2021-02-01 15:10:02,426 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:10:02,434 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:10:02,544 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:10:02,544 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:10:02,586 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356138227420889088], 'status': 2}
2021-02-01 15:16:20,529 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:16:20,529 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:16:20,529 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:16:20,639 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzExMDMsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.OKTtrT_Pi9noS6nfD6GThWjspJEGRmvrOChq2l2nnzE'}
2021-02-01 15:16:20,639 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:16:20,649 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:16:20,759 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:16:20,759 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:16:20,759 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:16:20,759 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:16:20,769 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:16:20,959 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzExMDIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.AThtn3OtnER287WNl1O7dAeZ9tGbLQHO7p-YnsrKZrM'}
2021-02-01 15:16:20,959 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:16:20,969 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:16:21,079 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:16:21,079 ERROR [test02_mis.py(test02_mis_search:42)] - 
2021-02-01 15:16:21,119 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356139815208222720], 'status': 2}
2021-02-01 15:18:49,959 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:18:49,959 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:18:49,959 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:18:50,099 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzEyNTIsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.g3GzWkZ9JypAjh_JtA5bNlxvrLa5i2ydCPnUdCekgdM'}
2021-02-01 15:18:50,099 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:18:50,109 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:18:50,199 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:18:50,209 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:18:50,209 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:18:50,209 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:18:50,209 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:19:05,448 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzEyNjcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.BT84ydw1FmpyxRV9KK07u_QypRm9FUAFzBlIq9Shqdg'}
2021-02-01 15:19:05,458 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:19:05,458 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:19:05,618 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:19:05,618 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 15:19:05,668 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356140442055344128], 'status': 2}
2021-02-01 15:23:56,461 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:23:56,461 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:23:56,461 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:23:56,601 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 15:23:56,641 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:23:56,751 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:23:56,751 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:23:56,751 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:23:56,751 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:23:56,941 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzE1NTgsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.BIgft_LcM6T0RzoCLMUBJFwnCL8bl82G7N7__0fpkCM'}
2021-02-01 15:23:56,941 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:23:56,951 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:23:57,041 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:23:57,051 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 15:23:57,051 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 15:24:18,339 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:24:18,339 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:24:18,339 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:24:18,450 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzE1ODAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.vOCvnXT5W3g65qs8ERAOHxiINzxi8T417T3KfUux4Dc'}
2021-02-01 15:24:18,450 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:24:18,459 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:24:18,559 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:24:18,569 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:24:18,569 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:24:18,569 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:24:18,569 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:24:18,819 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzE1ODEsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.jLtTy6eRtPK9jk_NZy_rAOMs3-FIhYzObay8cOJykDg'}
2021-02-01 15:24:18,819 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:24:18,829 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:24:18,929 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:24:18,929 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 15:24:18,969 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356141819297005568], 'status': 2}
2021-02-01 15:54:47,931 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:54:47,931 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:54:47,932 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:54:48,075 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzM0MTAsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.Si9cG5TNIm0LQziptkqnHxkUnwINtqssgG4bCBOcyvY'}
2021-02-01 15:54:48,075 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:54:48,083 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:54:48,204 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:54:48,211 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:54:48,211 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:54:48,211 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:54:48,212 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:54:48,411 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzM0MDksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.36S7UtAW3hTuPEPVOys1NXSjFWnlh_GOyCGVBHEfq3M'}
2021-02-01 15:54:48,412 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:54:48,422 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:54:48,553 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:54:48,554 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 15:54:48,598 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356149493434679296], 'status': 2}
2021-02-01 15:58:15,446 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 15:58:15,446 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 15:58:15,447 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 15:58:15,842 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzM2MTgsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.gYw2epd0HPAImpLvMRQdzN_7BSLN_UkeRC7QBhtDTAY'}
2021-02-01 15:58:15,842 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:58:15,850 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 15:58:15,954 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:58:15,963 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 15:58:15,963 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 15:58:15,963 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 15:58:15,964 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 15:58:16,165 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzM2MTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.LJtYQ2iTPHlh4cqk_J6-mfaBVPf8Fk7s7CFPNhl2vtY'}
2021-02-01 15:58:16,165 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:58:16,173 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 15:58:16,269 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 15:58:16,270 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 15:58:16,323 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356150364834889728], 'status': 2}
2021-02-01 16:14:28,922 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:14:28,922 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:14:28,923 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:14:29,169 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzQ1OTEsInVzZXJfaWQiOjEzMzE1NDIxNzM1MzkxMDY4MTYsInJlZnJlc2giOmZhbHNlLCJ2ZXJpZmllZCI6dHJ1ZX0.ZANtqlnuNEZVrM0UszJGD0RnOG3LUVg0NaSNEr1Spo0'}
2021-02-01 16:14:29,169 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:14:29,178 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:14:29,289 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:14:29,297 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:14:29,297 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:14:29,297 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:14:29,298 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:14:29,497 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzQ1OTEsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.GgfSJhxSgl2XGm-Ps0dHdShhRAZDhFc46gzGk9dr99Q'}
2021-02-01 16:14:29,498 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:14:29,506 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:14:29,622 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:14:29,623 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:14:29,666 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [1356154447314550784], 'status': 2}
2021-02-01 16:25:02,230 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:25:02,231 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:25:02,232 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:25:02,363 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:25:02,413 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:25:02,514 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:25:02,514 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:25:02,514 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:25:02,515 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:25:02,719 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzUyMjQsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.9WtL5y-SxrPNmTPv8e_cL3p2HRaYvwrrVxaff2N0jjQ'}
2021-02-01 16:25:02,720 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:25:02,728 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:25:02,840 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:25:02,840 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:25:02,851 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:32:48,211 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:32:48,211 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:32:48,212 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:32:48,343 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:32:48,391 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:32:48,497 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:32:48,497 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:32:48,497 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:32:48,498 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:32:48,698 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzU2ODksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.Yag_XuynNQ3rxJv4Buc1Qv2KKgd6o2rMsbU-fo6JWSk'}
2021-02-01 16:32:48,699 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:32:48,706 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:32:48,810 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:32:48,810 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:32:48,820 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:33:03,524 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:33:03,524 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:33:03,525 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:33:03,630 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:33:03,678 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:33:03,788 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:33:03,788 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:33:03,788 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:33:03,789 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:33:03,998 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzU3MDUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.1PNAdjoW5rBC_m6k6QSAEGx8XIMstx9nO7g1JdG1Hco'}
2021-02-01 16:33:03,999 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:33:04,008 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:33:04,118 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:33:04,118 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:33:04,130 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:50:32,418 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:50:32,418 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:50:32,419 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:50:32,551 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:50:32,599 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:50:32,698 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:50:32,699 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:50:32,699 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:50:32,700 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:50:32,916 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzY3NTUsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.FfrDzIlZy1oY2Yt5x34maILKoq9j6uJOJxAmiTangCQ'}
2021-02-01 16:50:32,917 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:50:32,924 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:50:33,028 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:50:33,028 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:50:33,038 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:50:48,679 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:50:48,679 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:50:48,680 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:50:48,786 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:50:48,834 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:51:04,033 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:51:04,033 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:51:04,033 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:51:04,034 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:51:19,230 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzY4MDAsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.y3hj3NgRWw82buhRSGLaJuW7uyhSNUwOH7Z5aX1Oh64'}
2021-02-01 16:51:19,230 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:51:19,239 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:51:19,342 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:51:19,342 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:51:19,352 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:52:45,548 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:52:45,549 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:52:45,549 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:52:45,695 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:52:45,744 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:52:45,873 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:52:45,873 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:52:45,873 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:52:45,874 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:52:46,105 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzY4ODgsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.1mKLXsPqotllcin0tsFVsXxX05YW6sMJieCxDkADM0g'}
2021-02-01 16:52:46,106 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:52:46,114 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:52:46,234 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:52:46,234 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:52:46,244 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:54:00,812 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:54:00,813 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:54:00,813 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:54:00,949 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:54:00,996 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:54:01,099 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:54:01,099 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:54:01,099 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:54:01,100 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:54:01,283 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzY5NjMsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.TucVIF2dU1MVRc_FURQFMtpUKNlIfHNFvMHfD2uIEMw'}
2021-02-01 16:54:01,284 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:54:01,293 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:54:01,386 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:54:01,386 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:54:01,397 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:54:15,181 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:54:15,182 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:54:15,183 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:54:15,289 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:54:15,335 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:54:15,442 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:54:15,442 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:54:15,442 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:54:15,443 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:54:15,645 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzY5NzgsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.5ZUJQrfd9zwTsD-grw0E0UCiI0IDTq6CwUaRTFAl2dI'}
2021-02-01 16:54:15,646 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:54:15,653 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:54:30,763 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:54:30,763 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:54:30,773 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 16:55:39,103 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 16:55:39,103 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 16:55:39,104 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 16:55:39,209 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 16:55:39,261 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 16:55:39,366 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 16:55:39,366 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 16:55:39,366 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cnmis/v1_0/articles
2021-02-01 16:55:39,367 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 16:55:39,601 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzcwNjIsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.dfeqoK2LPSqiN_sKVyzAUsnFaa7JTzra9UgpA-SMhtU'}
2021-02-01 16:55:39,601 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:55:39,609 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 16:55:39,710 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 16:55:39,711 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 16:55:39,721 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 17:36:17,716 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 17:36:17,716 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 17:36:17,717 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 17:36:17,848 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 17:36:17,896 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 17:36:18,010 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 17:36:18,010 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 17:36:18,010 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 17:36:18,011 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 17:36:18,209 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzk0OTksImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.ka6wXMYvfk1eKBUv4oY2maIjfFMCW-W4DQ5wKg3XBt8'}
2021-02-01 17:36:18,209 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:18,217 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 17:36:18,347 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:18,347 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 17:36:18,357 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 17:36:18,494 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:18,494 ERROR [test02_mis.py(test03_mis_audit:56)] - 
2021-02-01 17:36:35,793 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 17:36:35,794 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 17:36:35,794 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 17:36:35,894 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 17:36:35,942 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 17:36:36,060 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 17:36:36,061 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 17:36:36,061 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 17:36:36,062 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 17:36:36,259 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxNzk1MTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.URgA0w3uXq4gzeEW4c_WrW4hs-prn1qNSt4yXX01kt4'}
2021-02-01 17:36:36,260 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:36,268 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 17:36:36,372 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:36,372 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 17:36:36,383 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 17:36:36,485 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 17:36:36,485 ERROR [test02_mis.py(test03_mis_audit:56)] - 
2021-02-01 18:51:38,867 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 18:51:38,867 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 18:51:38,868 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 18:51:38,977 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 18:51:39,022 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 18:51:39,122 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 18:51:39,122 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 18:51:39,122 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 18:51:39,123 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 18:51:39,347 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxODQwMjEsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.uDjttF7g9Rr9jx_sAikHmxfZz9NOpQNDOTdIs_ygXCM'}
2021-02-01 18:51:39,348 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:51:39,355 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 18:51:39,450 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:51:39,450 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 18:51:39,460 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 18:51:39,561 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:51:39,561 ERROR [test02_mis.py(test03_mis_audit:56)] - 
2021-02-01 18:52:14,450 INFO [api_mp.py(__init__:12)] - 正在初始化自媒体登录url: http://ttapi.research.itcast.cn/mp/v1_0/authorizations
2021-02-01 18:52:14,451 INFO [api_mp.py(__init__:15)] - 正在初始化自媒体发布文章url
2021-02-01 18:52:14,452 INFO [api_mp.py(api_mp_login:27)] - 正在调用自媒体登录接口，请求数据：{'mobile': '13812345678', 'code': '246811'}
2021-02-01 18:52:14,559 ERROR [test01_mp.py(test01_mp_login:30)] - 'NoneType' object has no attribute 'get'
2021-02-01 18:52:14,607 INFO [api_mp.py(api_mp_article:42)] - 正在调用自媒体发布文章接口，请求数据：{'title': 'test-inter-001', 'content': '今天天气不错，适合做接口测试!', 'channel_id': '7', 'cover': {'type': 0, 'images': []}}
2021-02-01 18:52:14,713 INFO [api_mis.py(__init__:13)] - 正在初始化后台管理 登录url：http://ttapi.research.itcast.cn/mis/v1_0/authorizations
2021-02-01 18:52:14,713 INFO [api_mis.py(__init__:16)] - 正在初始化后台管理 查询文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 18:52:14,714 INFO [api_mis.py(__init__:19)] - 正在初始化后台管理 审核文章url：http://ttapi.research.itcast.cn/mis/v1_0/articles
2021-02-01 18:52:14,714 INFO [api_mis.py(api_mis_login:31)] - 正在调用后台管理系统 登录接口，请求数据为：{'account': 'testid', 'password': 'testpwd123'}
2021-02-01 18:52:14,928 INFO [tool.py(common_token:15)] - 正在提取token，提取后的header为：{'Content-Type': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIxODQwNTcsImFkbWluaXN0cmF0b3JfaWQiOjIsInJlZnJlc2giOmZhbHNlfQ.ylzS_7hSymH7ujFElEk7qVH9Lp5sfT2c9Lxuw-mPwMc'}
2021-02-01 18:52:14,929 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:52:14,937 INFO [api_mis.py(api_mis_search:44)] - 正在调用后台管理 查询文章接口，请求数据为：{'title': 'test-inter-001', 'channel': '数据库'}
2021-02-01 18:52:15,040 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:52:15,040 ERROR [test02_mis.py(test02_mis_search:43)] - 
2021-02-01 18:52:15,050 INFO [api_mis.py(api_mis_audit:57)] - 正在调用后台管理 审核文章接口，请求数据为：{'article_ids': [None], 'status': 2}
2021-02-01 18:52:15,150 INFO [tool.py(common_assert:21)] - 正在调用公共断言方法
2021-02-01 18:52:15,150 ERROR [test02_mis.py(test03_mis_audit:56)] - 
